RedHatInsights/astro-virtual-assistant

actions/slot_match.py
tests/actions/test_slot_match.py

This allows to match "RHEL" with "rhel"

RHCLOUD-31628 Ignore input case in slot_match

---

actions/feedback_actions.py
data/access/rules.yml
data/access/stories.yml
data/closing/domain.yml
data/domain.yml
data/feedback/domain.yml
data/openshift/stories.yml
tests/stories/openshift/test_openshift.yml

- Removed duplicate affirmation
- Adding closing redirects to openshift flows
- Update capabilities
- Added "yes" to is it a bug responses
- permissions flow fix (I think)

Bulk small fixes

---

data/domain.yml
data/notifications/rules.yml
data/rules.yml
data/stories.yml
tests/stories/test_first_time_setup.yml

So PII Warning will come up on all chats opening
@jrwho This will probably break your tests.

Adding pii_warning to not first time greeting

---

actions/insights/advisor_actions.py
common/requests.py
data/insights/advisor/domain.yml

RHCLOUD-30549, RHCLOUD-30550 New advisor recommendation flows

---

dashboards/grafana-dashboard-insights-virtual-assistant-general.configmap.yaml

- Do not consider 4xx in error rate
- Update latency to match our SLOs

Update grafana's dashboard

---

data/access/nlu.yml
data/feedback/nlu.yml
data/integrations/domain-edit.yml
data/integrations/domain.yml
data/nlu.yml
tests/stories/insights/image_builder/test_image_builder_custom_content.yml
tests/stories/insights/image_builder/test_image_builder_launch.yml
tests/stories/notifications/test_notifications_edit.yml
tests/stories/notifications/test_notifications_set_up.yml
tests/stories/test_data_deletion_request.yml
tests/stories/test_unknown_topic.yml

- Removing tests that cause troubles mostly entities that are recognized sometimes

Stabilize tests

---

actions/platform/notifications_actions.py
data/notifications/domain.yml
data/notifications/nlu.yml
data/notifications/rules.yml
tests/stories/notifications/test_notifications_edit.yml
tests/stories/notifications/test_notifications_set_up.yml

- Uncommenting it
- Wording
- Breaking form if the user doesn't get matched
- still need to think of a way to give multiple chances/figure out what they mean more :thinking:

Notifications fixes

---

actions/actions.py
actions/closing_actions.py
actions/feedback_actions.py
actions/insights/advisor_actions.py
actions/insights/vulnerability_actions.py
actions/platform/integrations/__init__.py
actions/platform/integrations/add_integration.py
actions/platform/integrations/edit_integration.py
common/metrics.py
data/closing/domain.yml

Still need to add the metric to more flows or at least key flows that we want to start tracking.

RHCLOUD-31713 Adding metrics for flow started/finished

---

build_deploy.sh

Have `.docker` dir somewhere else

Follow recommendations on build_deploy

---

.dockerignore

as suggested in https://github.com/RedHatInsights/cloud-connector/pull/259

Adds .dockerignore

---

actions/insights/advisor_actions.py

Allows to recognize typed text  "new recommendation" (or recent, etc) as the slot input.

RHCLOUD-31766 Recognize multiple words in advisor's flow

---

actions/insights/advisor_actions.py
common/config/app.py
common/requests.py
data/insights/advisor/domain.yml
deploy/clowdapp.yaml
tests/resources/clowdapp-redis.json
tests/resources/clowdapp-with-db-ca.json
tests/resources/clowdapp.json

RHCLOUD-29988 Advisor for OpenShift

---

actions/insights/advisor_actions.py
common/config/app.py
common/requests.py
data/insights/advisor/domain.yml
deploy/clowdapp.yaml
tests/resources/clowdapp-redis.json
tests/resources/clowdapp-with-db-ca.json
tests/resources/clowdapp.json

Reverting this one until all the backend configuration is in place.

RHCLOUD-29988 Revert Advisor for OpenShift

---

actions/platform/notifications/__init__.py
actions/platform/notifications/notifications_actions.py
actions/platform/notifications/troubleshoot_notifications.py
data/notifications/domain.yml
data/notifications/nlu.yml
data/notifications/rules-troubleshoot.yml

- Added troubleshoot flow, refactored some stuff for it
- Wasn't exiting from notifications if it had errored during the request (whoops)

Troubleshoot notifications

---

common/config/app.py
internal/endpoints.py
internal/utils.py

- Access to all data (filtered some sensitive information)
- Support for cursor pagination (useful when loading the chat)
- Merged messages API to use common code
- Using a default internal api port to simplify development
- senders API sorts by "latest activity from user" to show last users that were active and hides when there is only
interaction from our side (i.e. they  opened, bot said hi but they never typed anything)

RHCLOUD-31490 Update internal service to provide more information

---

data/nlu.yml

JIRA: https://issues.redhat.com/browse/RHCLOUD-32379

add some capabilities dialog

---

data/integrations/nlu.yml
data/notifications/nlu.yml

[doc](https://docs.google.com/spreadsheets/d/1DPKdcbuIWsh5U7RPEF1g16qtWkd-a6_Wj1mVEPQJcqA/edit#gid=2026575553)

More notifications and integrations examples from Jess

---

internal/endpoints.py

- It takes into account that id is incremental and correlated with the timestamp
This query is timing out - probably because i'm using max's. This is not really needed as we know that id is incremental and higher ids are higher timestamps. We just need to get the first ocurrence in descending order.

Update senders query to make use of the id as key

---

actions/platform/access_actions.py
data/access/domain.yml
data/access/nlu.yml
data/access/rules.yml

```
Your input ->  whats my org id
Your Org ID is org123. You can also find it by clicking on your name at the top right of the screen.
How would you rate our conversation?
Custom json:
{
"type": "command",
"command": "thumbs"
}
Your input ->
```

User can ask where's my org id

---

actions/closing_actions.py

This broke the feedback flow :thinking:. Need to figure out a better way for resetting these like we talked about.
https://issues.redhat.com/browse/RHCLOUD-32580

Removing condition for non-null closing type

---

actions/feedback_actions.py
data/domain.yml
data/feedback/domain.yml
data/feedback/nlu.yml
data/feedback/rules.yml
data/nlu.yml
tests/stories/feedback/test_feedback.yml

https://issues.redhat.com/browse/RHCLOUD-32518
https://issues.redhat.com/browse/RHCLOUD-32516

Immediate support needed in the feedback flow

---

actions/platform/2fa/enable_disable_2fa.py
data/2fa/domain.yml
data/2fa/nlu.yml
data/2fa/rules.yml
tests/stories/2fa/test_disable_2fa.yml
tests/stories/2fa/test_enable_2fa.yml

[RHCLOUD-32558] Disable 2fa

---

data/favorites/nlu.yml

https://issues.redhat.com/browse/RHCLOUD-32672 
Add some options for favoriting dialogue.

add favoriting dialog options

---

channels/console.py

Checking if this API plays any role in the alert

RHCLOUD-32861 Disable first_visit api

---

dashboards/grafana-dashboard-insights-virtual-assistant-general.configmap.yaml

Added one section for each service
Each section has its own memory and cpu graphs.

Adds CPU and memory usage to grafana

---

actions/core_actions.py
actions/platform/tam/__init__.py
actions/platform/tam/setup_actions.py
actions/platform/tam/tam_request.py
common/rasa/tracker.py
common/requests.py
data/access/tam/domain.yml
data/access/tam/nlu.yml
data/access/tam/rules.yml
data/domain.yml

```
Your input ->  i am a tam
I can help make a custom access request.
Please provide the customer's Account ID.
Your input ->  123
What is their Org ID?
Your input ->  123
? How long do you need access for? Select a preset below. 1: 3 days (3 days)
This request will grant you access to all roles in the customer account. For more granular access, use the form [here](/internal/access-requests).
? Are you sure you want to request access to customer account 123? 1: Yes (/intent_core_yes)
Your request for access to customer account 123 has been submitted. The customer will be notified shortly.
Future requests can also be made using the form [here](/internal/access-requests).
```
[Doc on the RBAC endpoint](https://spaces.redhat.com/pages/viewpage.action?pageId=472848321)

TAM Request

---

data/favorites/domain.yml

per https://issues.redhat.com/browse/RHCLOUD-32992

fix typo in favorites flow

---

app.py
channels/console.py
logging-config.yml
run_actions.py

This PR configures logging for our channels and our custom code.
- Configures logging for astro-virtual-assistant
- Allows to configure rasa in debug mode with LOG_LEVEL environment variable
-  Adds more debug logging into console's channel

Adding more logging information

---

deploy/clowdapp.yaml

- Did some light testing and looks like the cpu could be bounding our request rate

Update CPU requirements

---

data/access/nlu.yml
data/insights/subscriptions/nlu.yml
data/nlu.yml

Adding more examples, will make other changes later.

NLU additions from Jess

---

data/tours/domain.yml
data/tours/nlu.yml
data/tours/stories.yml

Adding back tour data

---

data/access/domain.yml
data/access/nlu.yml
data/insights/image_builder/nlu.yml
data/nlu.yml
data/rhel/domain.yml
data/rhel/nlu.yml
data/rhel/rules.yml

- RHEL Capabilities
- Correcting access capabilities payloads
- Adding more (admittedly why cant the bot handle these) simple examples to access, image builder, preferences, data deletion flows.
https://issues.redhat.com/browse/RHCLOUD-33411
https://issues.redhat.com/browse/RHCLOUD-33412
https://issues.redhat.com/browse/RHCLOUD-31996
https://issues.redhat.com/browse/RHCLOUD-31936

RHEL Capabilities + More NLU Fixes

---

data/nlu.yml

Ticket: [RHCLOUD-33830 ](https://issues.redhat.com/browse/RHCLOUD-33830)

add core capability NLU phrases

---

data/service_accounts/domain.yml

Ticket: [RHCLOUD-32967](https://issues.redhat.com/browse/RHCLOUD-32967)

fix and improve some spelling in api-integration flow

---

tests/extract_stories_nlu.py

Fix extract_stories.py

---

actions/insights/advisor_actions.py
data/insights/advisor/domain.yml
data/insights/advisor/nlu.yml
data/insights/advisor/rules.yml

https://github.com/user-attachments/assets/edc2e0e6-86af-4917-b3ae-f5e5579ccc85
https://github.com/user-attachments/assets/552ebb71-ef22-419c-87b2-9b4e52e74526

RHCLOUD-33435 Advisor for OpenShift clusters

---

actions/insights/advisor_actions.py
data/insights/advisor/domain.yml

RHCLOUD-33434 Implement Workloads in OpenShift for Advisor

---

data/access/nlu.yml
data/insights/subscriptions/nlu.yml
data/integrations/nlu.yml
data/nlu.yml

https://docs.google.com/spreadsheets/d/10u799kreVDnb708alQhvnZLxBj4NABdRmeUESXqBwRo/edit?gid=0#gid=0

August 2024 intent updates

---

actions/insights/subscriptions_actions.py
data/insights/subscriptions/domain.yml
data/insights/subscriptions/nlu.yml
data/insights/subscriptions/rules.yml
tests/stories/insights/subscriptions/test_subscriptions_rules.yml

Jiras:
* RHCLOUD-34682
* RHCLOUD-34683
* RHCLOUD-34685

Subscription Flows (SU5, SU6, SU8)

---

data/insights/subscriptions/domain.yml

Updating subscription flow utterances

---

data/domain.yml
data/nlu.yml
data/rules.yml

```
Your input ->  speak french?
I'm sorry, console.redhat.com and its services are only available in English.
To help me understand your questions, please ask them in English.
How would you rate our conversation?
Custom json:
{
"type": "command",
"command": "thumbs"
}
```

Other languages flow

---

data/nlu.yml

I'm hoping these won't bog the model down too bad :crossed_fingers:

Other languages - More examples

---

data/ansible/domain.yml
data/ansible/nlu.yml
data/ansible/rules.yml

Jira: https://issues.redhat.com/browse/RHCLOUD-32343, https://issues.redhat.com/browse/RHCLOUD-32344

Add ansible automation and trial workflows.

---

docker/Dockerfile.astro-virtual-assistant-internal
docker/Dockerfile.astro-virtual-assistant-rasa
docker/Dockerfile.astro-virtual-assistant-rasa-actions

Tried out by building these 3 images locally. They look good to me, at least on my machine.

Dockerfiles: removing redundant venv environment creation

---

libs/common/src/common/config/__init__.py
libs/common/src/common/config/app.py
services/watson-extension/src/watson-extension/config.py
services/watson-extension/src/watson-extension/run.py

This should help us keep our config organized by each service that we want to run and prevent conflicting configs with more stuff than needed

Created a specific config file for watson-extension

---

libs/common/src/common/session_storage/file.py
libs/common/src/common/session_storage/redis.py
libs/common/tests/common/session_storage/test_redis_session_storage.py
pyproject.toml
services/virtual-assistant/src/virtual-assistant/run.py
uv.lock

The redis instance is running using docker, so that would be only requirement to run the tests. 
They are currently running in github actions.
Had to change the way we construct the session storage to make it easier to test.

Adds redis tests

---

services/virtual-assistant/src/virtual_assistant/api_types.py
services/virtual-assistant/src/virtual_assistant/watson.py

Parsing command types in our API
Also threw in a naming fix. Was getting error ```TypeError: WatsonAssistantImpl.send_watson_message() got an unexpected keyword argument 'user_id'```. We can change it back the other way if that makes sense too :)

Command types

---

services/virtual-assistant/src/virtual_assistant/routes/talk.py
services/virtual-assistant/src/virtual_assistant/startup.py
services/virtual-assistant/src/virtual_assistant/watson.py
services/virtual-assistant/tests/__init__.py
services/virtual-assistant/tests/routes/test_talk.py
services/virtual-assistant/tests/test_watson.py

- This should prevent any stalling waiting for IO responses

Making watson api async

---

libs/common/src/common/config/__init__.py
libs/common/src/common/logging.py
services/virtual-assistant/pyproject.toml
services/virtual-assistant/src/run.py
services/virtual-assistant/src/virtual_assistant/config.py
services/virtual-assistant/src/virtual_assistant/routes/talk.py
services/watson-extension/src/run.py
services/watson-extension/src/watson_extension/config.py
uv.lock

- Allows to select one in the configuration
- Defaults to basic (console)
- Adds dependencies

Logging configuration

---

pyproject.toml
services/watson-extension/src/watson_extension/auth/__init__.py
services/watson-extension/src/watson_extension/auth/api_key_authentication.py
services/watson-extension/src/watson_extension/auth/no_authentication.py
services/watson-extension/src/watson_extension/config.py
services/watson-extension/src/watson_extension/startup.py
services/watson-extension/tests/auth/test_auth_api_key.py
services/watson-extension/tests/auth/test_no_auth.py
uv.lock

- using no-auth or api-key based auth
- defaults to no auth

Add minimal auth code

---

services/watson-extension/src/watson_extension/auth/service_account_authentication.py
services/watson-extension/src/watson_extension/config.py
services/watson-extension/src/watson_extension/startup.py
services/watson-extension/tests/auth/test_auth_api_key.py
services/watson-extension/tests/auth/test_auth_service_account.py
services/watson-extension/tests/resources/auth/identity-header.json

We will define a specific service account (by its client_id)

RHCLOUD-37505 Adds service account authentication for watson-extension

---

data/rhel/domain.yml
data/rhel/nlu.yml
data/rhel/rules.yml

Jira: https://issues.redhat.com/browse/RHCLOUD-40067

RHCLOUD-40067 Adding rhel planning flow
